# Generated by Django 2.2.5 on 2019-09-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_auto_20190922_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantcode', models.IntegerField(default=642616)),
                ('amount', models.PositiveIntegerField()),
                ('token', models.IntegerField(default=10000)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cart.Cart')),
            ],
        ),
    ]
