# Generated by Django 2.2.5 on 2019-09-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantcode', models.IntegerField(default=642616)),
                ('amount', models.PositiveIntegerField()),
                ('token', models.IntegerField(default=10000)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=20, null=True)),
                ('paid_on', models.CharField(blank=True, max_length=20, null=True)),
                ('method', models.CharField(blank=True, max_length=1, null=True)),
                ('administative_charge', models.CharField(blank=True, max_length=20, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cart.Cart')),
            ],
        ),
    ]
