# Generated by Django 2.2.5 on 2019-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('ACURA', 'Acura'), ('ALFAROMEO', 'Alfa Romeo'), ('ASTONMARTIN', 'Aston Martin'), ('AUDI', 'Audi'), ('BENTLEY', 'Bentley'), ('BMW', 'BMW'), ('BUICK', 'Buick'), ('CADILLAC', 'Cadillac'), ('CHEVROLET', 'Chevrolet'), ('CHRYSLER', 'Chrysler'), ('DODGE', 'Dodge'), ('FERRARI', 'Ferrari'), ('FIAT', 'FIAT'), ('FORD', 'Ford'), ('GENESIS', 'Genesis'), ('GMC', 'GMC'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('INFINITI', 'INFINITI'), ('JAGUAR', 'Jaguar'), ('JEEP', 'Jeep'), ('KIA', 'Kia'), ('LAMBORGHINI', 'Lamborghini'), ('LANDROVER', 'Land Rover'), ('LEXUS', 'Lexus'), ('LINCOLN', 'Lincoln'), ('LOTUS', 'Lotus'), ('MASERATI', 'Maserati'), ('MAZDA', 'Mazda'), ('MCLAREN', 'McLaren'), ('MERCEDESBENZ', 'Mercedes-Benz'), ('MINI', 'MINI'), ('MITSUBISHI', 'Mitsubishi'), ('NISSAN', 'Nissan'), ('PORSCHE', 'Porsche'), ('RAM', 'RAM'), ('ROLLSROYCE', 'Rolls-Royce'), ('SCION', 'Scion'), ('SMART', 'smart'), ('SUBARU', 'Subaru'), ('TESLA', 'Tesla'), ('TOYOTA', 'Toyota'), ('VOLKSWAGEN', 'Volkswagen'), ('VOLVO', 'Volvo')], max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('gear', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('milage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
